/**
 * @arcpay/b2b Type Definitions
 *
 * Export all types from this central location
 */

// Common types
export type {
  ArcPayB2BConfig,
  PaginationParams,
  PaginatedList,
  ApiResponse,
  ApiError,
  Currency,
  Money,
  PaymentStatus,
  SettlementStatus,
  Metadata,
  Identifiable,
  Timestamped,
  BlockchainAddress,
  Chain,
  Organization,
} from './common';

// Credit & Usage types
export type {
  CreditAccount,
  CreditAccountStatus,
  CreditAccountSettings,
  AutoTopUpConfig,
  CreateCreditAccountParams,
  UpdateCreditAccountParams,
  DepositParams,
  DepositMethod,
  Deposit,
  DepositStatus,
  ListCreditAccountsParams,
  RateCard,
  Rate,
  RateTier,
  UsageRecord,
  RecordUsageParams,
  UsageSummary,
  UsageSummaryItem,
  ListUsageParams,
  BalanceSnapshot,
  TransferToYieldParams,
  TransferFromYieldParams,
  CreditEventType,
  CreditEvent,
} from './credit';

// Dispute types
export type {
  Dispute,
  DisputeCategory,
  DisputeStatus,
  DesiredResolution,
  Evidence,
  EvidenceType,
  MerchantResponse,
  AIEvaluation,
  EvaluationFactors,
  PartyHistoryAnalysis,
  EvidenceQualityAnalysis,
  TransactionAnalysis,
  DisputeResolution,
  CreateDisputeParams,
  CreateEvidenceParams,
  RespondToDisputeParams,
  ListDisputesParams,
  DisputeProtectionSettings,
  UpdateDisputeProtectionParams,
  DeliveryProof,
  DeliveryType,
  DeliveryProofDetails,
  RegisterDeliveryParams,
  DisputeEventType,
  DisputeEvent,
} from './dispute';

// Gateway types
export type {
  Invoice,
  InvoiceStatus,
  BuyerInfo,
  LineItem,
  PaymentDetails,
  SettlementDetails,
  CreateInvoiceParams,
  CreateLineItemParams,
  UpdateInvoiceParams,
  ListInvoicesParams,
  MerchantSettings,
  SettlementConfig,
  MerchantBranding,
  UpdateMerchantSettingsParams,
  BatchPayment,
  BatchStatus,
  BatchPaymentItem,
  CreateBatchPaymentParams,
  CreateBatchPaymentItemParams,
  ListBatchPaymentsParams,
  GatewayEventType,
  GatewayEvent,
} from './gateway';

// Treasury types
export type {
  TreasuryAccount,
  TreasuryStatus,
  TreasuryFund,
  TreasuryVault,
  TreasuryStrategy,
  OperatingStrategy,
  ReserveStrategy,
  VaultStrategy,
  RebalanceFrequency,
  CreateTreasuryParams,
  UpdateTreasuryParams,
  TreasuryOverview,
  FundOverview,
  VaultOverview,
  TreasuryTransaction,
  TreasuryTransactionType,
  TreasuryFundType,
  TreasuryTransactionStatus,
  TreasuryPaymentParams,
  TreasuryPaymentResult,
  PaymentSourceBreakdown,
  ConversionDetails,
  RebalanceRequest,
  RebalanceResult,
  RebalanceSchedule,
  TreasuryAlert,
  TreasuryAlertType,
  AlertSeverity,
  ListTreasuryTransactionsParams,
  TreasuryEventType,
  TreasuryEvent,
} from './treasury';

// Webhook types
export type {
  WebhookEventType,
  WebhookEvent,
  WebhookEndpoint,
  WebhookEndpointStatus,
  CreateWebhookEndpointParams,
  UpdateWebhookEndpointParams,
  WebhookDelivery,
  WebhookDeliveryStatus,
  WebhookSignatureHeader,
  VerifyWebhookParams,
  WebhookHandler,
  WebhookHandlers,
} from './webhook';

// USDY Yield types
export type {
  UsdyStats,
  UsdyTransaction,
  UsdyTransactionType,
  UsdyTransactionStatus,
  DepositParams as UsdyDepositParams,
  WithdrawParams as UsdyWithdrawParams,
  ListUsdyTransactionsParams,
  AutomationRule,
  AutomationRuleType,
  AutomationRuleConfig,
  CreateAutomationRuleParams,
  UpdateAutomationRuleParams,
  AutomationLog,
  AutomationTriggerType,
  TriggerRuleParams,
  YieldAccrual,
  ApyHistoryEntry,
  ListYieldHistoryParams,
  UsdyEventType,
  UsdyEvent,
} from './usdy';

// x402 Gateway types
export type {
  GatewayBalance,
  CombinedBalances,
  SupportedNetwork,
  PaymentRequirements,
  PaymentPayload,
  VerifyResult,
  SettleResult,
  CrossChainWithdrawParams,
  CrossChainWithdrawResult,
  GatewaySellerConfig,
  UpsertSellerConfigParams,
  GatewayPayment,
  ListGatewayPaymentsParams,
  X402EventType,
  X402Event,
} from './x402';
